import { createAdminClient } from '@/lib/supabase/admin';
import { getASRService, getTranslationService, getClassificationService } from '@/lib/services';
import { TelephonyWebhookInput, TelephonyWebhookOutput } from '@/lib/services/types';
import { config } from '@/lib/config';

export async function processIncomingCall(
  payload: TelephonyWebhookInput
): Promise<TelephonyWebhookOutput> {
  const supabase = createAdminClient();
  const asrService = getASRService();
  const translationService = getTranslationService();

  // 1. ASR: transcribe audio
  const asrResult = await asrService.transcribe({
    audio_url: payload.audio_url,
    language_hint: payload.dtmf_language,
  });

  // 2. Translation: translate to urdu + english
  const translationResult = await translationService.translate({
    text: asrResult.transcript,
    source_lang: asrResult.language_detected,
  });

  // 3. Fetch departments for classification
  const { data: departments } = await supabase.from('departments').select('id, name, keywords');

  const classificationService = getClassificationService(
    (departments || []).map((d) => ({
      id: d.id,
      name: d.name,
      keywords: d.keywords || [],
    }))
  );

  // 4. Classification
  const classificationResult = await classificationService.classify({
    text: translationResult.english,
  });

  // 5. Low-confidence gate
  const isLowConfidence =
    asrResult.confidence < config.classification.asrConfidenceThreshold ||
    classificationResult.confidence < config.classification.confidenceThreshold;
  const status = isLowConfidence ? 'needs_review' : 'open';
  const departmentId = isLowConfidence ? null : classificationResult.department_id;

  // 6. Upsert citizen (if caller_id provided)
  let citizenId: string | null = null;
  if (payload.caller_id) {
    // Hash the phone number for privacy (simple approach for MVP)
    const phoneHash = payload.caller_id; // In production, use a proper hash

    // Try to find existing citizen
    const { data: existingCitizen } = await supabase
      .from('citizens')
      .select('id')
      .eq('phone_hash', phoneHash)
      .single();

    if (existingCitizen) {
      citizenId = existingCitizen.id;
    } else {
      const { data: newCitizen } = await supabase
        .from('citizens')
        .insert({
          phone_hash: phoneHash,
          preferred_language: asrResult.language_detected,
        })
        .select('id')
        .single();
      citizenId = newCitizen?.id || null;
    }
  }

  // 7. Insert complaint (tracking_id auto-generated by Postgres sequence)
  const { data: complaint, error: complaintError } = await supabase
    .from('complaints')
    .insert({
      citizen_id: citizenId,
      department_id: departmentId,
      category: classificationResult.category,
      audio_url: payload.audio_url,
      transcript_regional: asrResult.transcript,
      transcript_urdu: translationResult.urdu,
      transcript_english: translationResult.english,
      confidence_score: classificationResult.confidence,
      status,
      area: null,
    })
    .select('id, tracking_id')
    .single();

  if (complaintError || !complaint) {
    throw new Error(`Failed to create complaint: ${complaintError?.message}`);
  }

  // 8. Insert call_log
  await supabase.from('call_logs').insert({
    call_ref: payload.call_ref,
    duration_sec: 0, // Will be updated by telephony provider
    language_selected: payload.dtmf_language,
    outcome: 'completed',
    complaint_id: complaint.id,
  });

  // 9. Insert initial status_history row
  await supabase.from('status_history').insert({
    complaint_id: complaint.id,
    status,
    remark: 'Complaint received via phone call',
    updated_by: null, // System-generated
  });

  // 10. Return tracking_id and confirmation
  return {
    tracking_id: complaint.tracking_id,
    spoken_confirmation_text: `Your complaint has been registered. Your tracking ID is ${complaint.tracking_id}. Please save this for future reference.`,
  };
}
